# Generated by Django 4.1.3 on 2022-12-04 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HojaAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesionalAtendio', models.CharField(max_length=25)),
                ('anamnesisAnterior', models.CharField(max_length=250)),
                ('medicamentosRecetados', models.CharField(max_length=250)),
                ('examenesSolicitados', models.CharField(max_length=250)),
                ('alergias', models.CharField(max_length=125)),
                ('historialEnfermedades', models.CharField(max_length=500)),
                ('medicamentosQueToma', models.CharField(max_length=250)),
                ('diagnosticoObtenido', models.CharField(max_length=500)),
                ('observaciones', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombres', models.CharField(max_length=50)),
                ('apellido_p', models.CharField(max_length=25)),
                ('apellido_m', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=25)),
                ('dateB', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(max_length=25)),
                ('Comuna', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=25)),
                ('emergencyContact', models.CharField(max_length=25)),
                ('emergencyPhone', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('health', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombres', models.CharField(max_length=50)),
                ('apellido_p', models.CharField(max_length=25)),
                ('apellido_m', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombres', models.CharField(max_length=50)),
                ('apellido_p', models.CharField(max_length=25)),
                ('apellido_m', models.CharField(max_length=25)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicApp.especialidades')),
            ],
        ),
    ]
